### PR TITLE
Create how-to-hire-good-developers.md

### PR DESCRIPTION
**Pull request by liiaang**
I just wrote some take aways about how to hire good developers in the future.

### CODE REVIEW

**Comment by liiaang** [comment]
@kellzpagez @dianamcho @marisakololyan 
hi! please give me feedback!

**Comment by dianamcho** [comment]
@liiaang I love the advice. In the 2nd paragraph, you meant to say "less experienced" but said "less experience". Minor typo

**Comment by marisakololyan** [comment]
Looks great Liang! Nothing to add

**Comment by liiaang** [comment]
@dianamcho, I fixed my typo. please give me a thumbs up!

**Comment by liiaang** [comment]
@marisakololyan, great to hear that! please give me a thumbs up!

**Comment by dianamcho** [comment]
:+1: love it @liiaang

**Comment by liiaang** [comment]
@kellzpagez, added those headers! please give me a thumbs up!

**Comment by marisakololyan** [comment]
Nice! :+1:

**Pull request merged**
