### PR TITLE
Create EmbarkingonSWDevelopment.md

### PR DESCRIPTION
**Pull request by marisakololyan**

### CODE REVIEW

**Comment by marisakololyan** [comment]
@liiaang @dianamcho @kellzpagez Please give me feedback!

**Comment by marisakololyan** [comment]
@liiaang and @dianamcho - can you give me a :+1: now?

**Comment by liiaang** [comment]
:+1:  whoooo!

**Comment by dianamcho** [comment]
:+1:  love it @marisakololyan You're the best! :wine_glass:

**Pull request merged**
