### PR TITLE
Create tipscreatingaleanstartup.md

### PR DESCRIPTION
**Pull request by kellzpagez**
This will be a good addition!

### CODE REVIEW

**Comment by kellzpagez** [comment]
@liiaang @dianamcho @marisakololyan Hi all!  Please give me feedback!

**Comment by kellzpagez** [comment]
@marisakololyan @dianamcho I made your requested changes.  can you check?

**Comment by liiaang** [comment]
:+1:  ready to :ship:

**Comment by marisakololyan** [comment]
:+1:

**Pull request merged**
