### PR TITLE
Create Bad-SW-Dev-Experiences.md

### PR DESCRIPTION
**Pull request by dianamcho**
Check out my bad past experiences and learnings for the future!

### CODE REVIEW

**Comment by dianamcho** [comment]
@liiaang @kellzpagez @marisakololyan check this out!

**Comment by dianamcho** [comment]
@liiaang @kellzpagez @marisakololyan please approve the changes with a :+1:

**Comment by liiaang** [comment]
:+1:

**Comment by marisakololyan** [comment]
:+1:

**Pull request merged**
